<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCxuvIDv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCxuvIDv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCxuvIDv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCxuvIDv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCxuvIDv\App_KernelDevDebugContainer([
    'container.build_hash' => 'CxuvIDv',
    'container.build_id' => 'dea1ae79',
    'container.build_time' => 1584113727,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCxuvIDv');
